# Generated by Django 3.0.1 on 2021-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=2000)),
                ('productImage', models.CharField(max_length=200)),
                ('shop', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
