# Generated by Django 3.0.1 on 2021-11-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211103_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shopName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=200),
        ),
    ]
